class processaLeitos:
    def __init__(self):
        self.hospital = {
            'ACENI': {'municipio': 420550, 'index_regional': 4},
            'ASSOCIACAO BENEFICENTE HOSPITAL SAO LUCAS': {'municipio': 420640, 'index_regional': 6},
            'ASSOCIAÇÃO BENEFICENTE HOSPITALAR SÃO CAMILO PERITIBA': {'municipio': 421260, 'index_regional': 4},
            'ASSOCIAÇÃO BENEFICIENTE HOSPITAL SÃO LUCAS': {'municipio': 420640, 'index_regional': 6},
            'ASSOCIAÇÃO HOSPITAL E MATERNIDADE DOM JOAQUIM': {'municipio': 420290, 'index_regional': 11},
            'ASSOCIAÇÃO HOSPITALAR ANGELINA MENEGHELLI': {'municipio': 421935, 'index_regional': 3},
            'ASSOCIAÇÃO HOSPITALAR DE VARGEÃO': {'municipio': 421910, 'index_regional': 17},
            'ASSOCIACAO HOSPITALAR PE JOAO BERTHIER': {'municipio': 421600, 'index_regional': 14},
            'ASSOCIAÇÃO HOSPITALAR PE JOÃO BERTHIER': {'municipio': 421600, 'index_regional': 14},
            'CENTRO DE CONVIVENCIA': {'municipio': 421660, 'index_regional': 9},
            'CENTRO HOSPITALAR UNIMED': {'municipio': 420910, 'index_regional': 13},
            'CEPON': {'municipio': 420540, 'index_regional': 9},
            'FUNDAÇÃO HOSPITALAR DE IMBUIA': {'municipio': 420740, 'index_regional': 3},
            'FUNDAÇÃO HOSPITALAR HENRIQUE LAGE': {'municipio': 420960, 'index_regional': 5},
            'FUNDAÇÃO HOSPITALAR MUNICIPAL DE CANELINHA': {'municipio': 420370, 'index_regional': 9},
            'FUNDACAO HOSPITALAR SANTA OTILIA': {'municipio': 421170, 'index_regional': 5},
            'FUNDAÇÃO HOSPITALAR SANTA OTÍLIA': {'municipio': 421170, 'index_regional': 5},
            'FUNDAÇÃO MEDICA ASSISTENCIAL DO TRABALHADOR RURAL': {'municipio': 420410, 'index_regional': 14},
            'FUNDAÇÃO MEDICA SOCIAL RURAL DE PONTE ALTA': {'municipio': 421330, 'index_regional': 16},
            'FUNDAÇÃO MEDICO SOCIAL RURAL DE SANTA CATARINA': {'municipio': 421270, 'index_regional': 3},
            'FUNDAÇÃO MEDICO SOCIAL RURAL DE SÃO MARTINHO': {'municipio': 421710, 'index_regional': 10},
            'HOSP. NOSSA SENHORA CONCEIÇÃO': {'municipio': 421870, 'index_regional': 10},
            'HOSPITAL AMERICO CAETANO DO AMARAL': {'municipio': 420250, 'index_regional': 16},
            'HOSPITAL AZAMBUJA': {'municipio': 420290, 'index_regional': 11},
            'HOSPITAL BEATRIZ RAMOS': {'municipio': 420750, 'index_regional': 11},
            'HOSPITAL BEIRA MAR': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL BENEFICENTE SAO ROQUE': {'municipio': 421003, 'index_regional': 12},
            'HOSPITAL BETHESDA': {'municipio': 420910, 'index_regional': 13},
            'HOSPITAL BOM JESUS': {'municipio': 420850, 'index_regional': 3},
            'HOSPITAL CAIBI': {'municipio': 420310, 'index_regional': 14},
            'HOSPITAL CEDRO': {'municipio': 421670, 'index_regional': 6},
            'HOSPITAL CIRURGICO CAMBORIU': {'municipio': 420320, 'index_regional': 8},
            'HOSPITAL CUNHA PORA': {'municipio': 420470, 'index_regional': 14},
            'HOSPITAL DA CRIANCA AUGUSTA MULLER BOHNER': {'municipio': 420420, 'index_regional': 14},
            'HOSPITAL DA FUNDACAO': {'municipio': 421690, 'index_regional': 17},
            'HOSPITAL DE ALFREDO WAGNER': {'municipio': 420070, 'index_regional': 9},
            'HOSPITAL DE CARIDADE': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL DE CARIDADE CORACAO DE JESUS': {'municipio': 421650, 'index_regional': 16},
            'HOSPITAL DE CARIDADE DE JAGUARUNA': {'municipio': 420880, 'index_regional': 10},
            'HOSPITAL DE CARIDADE DE SÃO ROQUE': {'municipio': 421120, 'index_regional': 10},
            'HOSPITAL DE CARIDADE DO CORAÇÃO DE JESUS': {'municipio': 421650, 'index_regional': 16},
            'HOSPITAL DE CARIDADE S B J DOS PASSOS': {'municipio': 420940, 'index_regional': 10},
            'HOSPITAL DE CARIDADE SAO ROQUE': {'municipio': 421120, 'index_regional': 5},
            'HOSPITAL DE GASPAR': {'municipio': 420590, 'index_regional': 11},
            'HOSPITAL DE IPORA': {'municipio': 420765, 'index_regional': 6},
            'HOSPITAL DE MODELO': {'municipio': 421090, 'index_regional': 14},
            'HOSPITAL DE PENHA': {'municipio': 421250, 'index_regional': 8},
            'HOSPITAL DE PINHALZINHO': {'municipio': 421290, 'index_regional': 14},
            'HOSPITAL DE POUSO REDONDO': {'municipio': 421370, 'index_regional': 3},
            'HOSPITAL DE RETAGUARDA RIO MAINA': {'municipio': 420460, 'index_regional': 5},
            'HOSPITAL DE RIO FORTUNA': {'municipio': 421490, 'index_regional': 10},
            'HOSPITAL DE SÃO BONIFÁCIO': {'municipio': 421590, 'index_regional': 9},
            'HOSPITAL DE TUNAPOLIS': {'municipio': 421875, 'index_regional': 6},
            'HOSPITAL DIVINO SALVADOR': {'municipio': 421900, 'index_regional': 4},
            'HOSPITAL DOM BOSCIO RIO DOS CEDROS SC': {'municipio': 421470, 'index_regional': 11},
            'HOSPITAL DOM JOAQUIM IMAS': {'municipio': 421770, 'index_regional': 7},
            'HOSPITAL DR JOSE ATHANAZIO': {'municipio': 420360, 'index_regional': 12},
            'HOSPITAL E MAT. MARIETA K. BORNHAUSEN': {'municipio': 420820, 'index_regional': 8},
            'HOSPITAL E MATENIDADE NOSSA SENHORA DA CONCEIÇÃO': {'municipio': 420090, 'index_regional': 9},
            'HOSPITAL E MATERNIDADE DONA LISETTE': {'municipio': 421780, 'index_regional': 3},
            'HOSPITAL E MATERNIDADE JARAGUÁ': {'municipio': 420890, 'index_regional': 13},
            'HOSPITAL E MATERNIDADE MARIA AUXILIADORA': {'municipio': 421400, 'index_regional': 3},
            'HOSPITAL E MATERNIDADE RIO DO TESTO': {'municipio': 421320, 'index_regional': 11},
            'HOSPITAL E MATERNIDADE SANTA CECILIA': {'municipio': 421550, 'index_regional': 4},
            'HOSPITAL E MATERNIDADE SANTA TEREZINHA': {'municipio': 421530, 'index_regional': 3},
            'HOSPITAL E MATERNIDADE TEREZA RAMOS': {'municipio': 420930, 'index_regional': 16},
            'HOSPITAL FAUSTINO RISCAROLI': {'municipio': 420455, 'index_regional': 16},
            'HOSPITAL FELIX DA COSTA GOMES': {'municipio': 421830, 'index_regional': 15},
            'HOSPITAL FLORIANÓPOLIS': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL FREI BRUNO': {'municipio': 421970, 'index_regional': 17},
            'HOSPITAL FREI ROGÉRIO': {'municipio': 420100, 'index_regional': 16},
            'HOSPITAL GOVERNADOR CELSO RAMOS': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL GUARUJÁ': {'municipio': 420660, 'index_regional': 6},
            'HOSPITAL HELIO ANJO ORTIZ': {'municipio': 420480, 'index_regional': 4},
            'HOSPITAL HOSCOLA': {'municipio': 421000, 'index_regional': 8},
            'HOSPITAL INFANTIL DR JESER AMARANTE FARIA': {'municipio': 420910, 'index_regional': 13},
            'HOSPITAL INFANTIL JOANA DE GUSMAO': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL INFANTIL SEARA DO DO BEM': {'municipio': 420930, 'index_regional': 16},
            'HOSPITAL INSTITUTO DE CARDIOLOGIA': {'municipio': 421660, 'index_regional': 9},
            'HOSPITAL IZOLDE HUBNER DALMORA': {'municipio': 420985, 'index_regional': 2},
            'HOSPITAL JOÃO SCHREIBER': {'municipio': 421060, 'index_regional': 13},
            'HOSPITAL MAICE': {'municipio': 420300, 'index_regional': 4},
            'HOSPITAL MATEUS CALED PADOIN': {'municipio': 421940, 'index_regional': 3},
            'HOSPITAL MISERICORDIA': {'municipio': 420240, 'index_regional': 11},
            'HOSPITAL MONDAI': {'municipio': 421100, 'index_regional': 6},
            'HOSPITAL MONSENHOR JOSE LOCKS DE SAO JOAO BATISTA': {'municipio': 421630, 'index_regional': 9},
            'HOSPITAL MONSENHOR JOSÉ LOCKS DE SÃO JOÃO BATISTA': {'municipio': 421630, 'index_regional': 9},
            'HOSPITAL MUNICIPAL BOM JESUS': {'municipio': 420790, 'index_regional': 15},
            'HOSPITAL MUNICIPAL FREI ROGERIO': {'municipio': 421790, 'index_regional': 4},
            'HOSPITAL MUNICIPAL NOSSA SENHORA DA GRAÇA': {'municipio': 421620, 'index_regional': 13},
            'HOSPITAL MUNICIPAL RUTH CARDOSO': {'municipio': 420200, 'index_regional': 8},
            'HOSPITAL MUNICIPAL SANTO ANTONIO': {'municipio': 420830, 'index_regional': 8},
            'HOSPITAL MUNICIPAL SÃO JOSÉ JOINVILLE': {'municipio': 420910, 'index_regional': 13},
            'HOSPITAL MUNICIPAL SÃO LUCAS': {'municipio': 421030, 'index_regional': 15},
            'HOSPITAL NEREU RAMOS': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL NOSSA SENHORA DA CONCEIÇÃO HNSC': {'municipio': 421870, 'index_regional': 10},
            'HOSPITAL NOSSA SENHORA DA IMACULADA CONCEICAO': {'municipio': 421150, 'index_regional': 9},
            'HOSPITAL NOSSA SENHORA DA PAZ': {'municipio': 420040, 'index_regional': 12},
            'HOSPITAL NOSSA SENHORA DA SAUDE CORONEL FREITAS': {'municipio': 420440, 'index_regional': 14},
            'HOSPITAL NOSSA SENHORA DAS DORES': {'municipio': 420390, 'index_regional': 12},
            'HOSPITAL NOSSA SENHORA DAS GRACAS': {'municipio': 420260, 'index_regional': 16},
            'HOSPITAL NOSSA SENHORA DAS GRAÇAS': {'municipio': 420260, 'index_regional': 16},
            'HOSPITAL NOSSA SENHORA DE FATIMA': {'municipio': 421380, 'index_regional': 7},
            'HOSPITAL NOSSA SENHORA DO PATROCINIO': {'municipio': 420340, 'index_regional': 16},
            'HOSPITAL NOSSA SENHORA DOS NAVEGANTES': {'municipio': 421130, 'index_regional': 8},
            'HOSPITAL NOSSA SENHORA DOS PRAZERES': {'municipio': 420930, 'index_regional': 16},
            'HOSPITAL NOVA ERECHIM': {'municipio': 421140, 'index_regional': 14},
            'HOSPITAL OASE': {'municipio': 421820, 'index_regional': 11},
            'HOSPITAL OSVALDO CRUZ': {'municipio': 420127, 'index_regional': 2},
            'HOSPITAL PALMA SOLA': {'municipio': 421200, 'index_regional': 6},
            'HOSPITAL PALMITOS': {'municipio': 421210, 'index_regional': 14},
            'HOSPITAL PIRATUBA IPIRA': {'municipio': 420760, 'index_regional': 2},
            'HOSPITAL REGIONAL ALTO VALE': {'municipio': 421480, 'index_regional': 3},
            'HOSPITAL REGIONAL ARARANGUÁ': {'municipio': 420140, 'index_regional': 7},
            'HOSPITAL REGIONAL DE BIGUACU HELMUTH NASS': {'municipio': 420230, 'index_regional': 9},
            'HOSPITAL REGIONAL DO OESTE': {'municipio': 420420, 'index_regional': 14},
            'HOSPITAL REGIONAL HANS DIETER': {'municipio': 420910, 'index_regional': 13},
            'HOSPITAL REGIONAL SÃO JOSÉ': {'municipio': 421660, 'index_regional': 9},
            'HOSPITAL REGIONAL SÃO PAULO': {'municipio': 421950, 'index_regional': 17},
            'HOSPITAL RIO NEGRINHO': {'municipio': 421500, 'index_regional': 15},
            'HOSPITAL ROGACIONISTA EVANGÉLICO': {'municipio': 420010, 'index_regional': 17},
            'HOSPITAL SAGRADA FAMILIA': {'municipio': 421580, 'index_regional': 15},
            'HOSPITAL SAMARIA': {'municipio': 421480, 'index_regional': 3},
            'HOSPITAL SANTA CASA RURAL': {'municipio': 421625, 'index_regional': 6},
            'HOSPITAL SANTA CATARINA': {'municipio': 420240, 'index_regional': 11},
            'HOSPITAL SANTA CLARA': {'municipio': 421175, 'index_regional': 16},
            'HOSPITAL SANTA CRUZ': {'municipio': 420380, 'index_regional': 15},
            'HOSPITAL SANTA ISABEL': {'municipio': 420240, 'index_regional': 11},
            'HOSPITAL SANTA JULIANA': {'municipio': 421540, 'index_regional': 4},
            'HOSPITAL SANTA LUZIA DE DEOLINDO JOSE BAGGIO': {'municipio': 421340, 'index_regional': 17},
            'HOSPITAL SANTA TERESA': {'municipio': 421725, 'index_regional': 9},
            'HOSPITAL SANTA TERESINHA': {'municipio': 420280, 'index_regional': 10},
            'HOSPITAL SANTA TEREZINHA': {'municipio': 420900, 'index_regional': 12},
            'HOSPITAL SANTO ANTONIO': {'municipio': 420240, 'index_regional': 11},
            'HOSPITAL SANTO ANTONIO CAMPO ERE': {'municipio': 420350, 'index_regional': 14},
            'HOSPITAL SANTO ANTONIO DE ITAIÓPOLIS': {'municipio': 420810, 'index_regional': 15},
            'HOSPITAL SANTO ANTONIO GUARAMIRIM': {'municipio': 420650, 'index_regional': 13},
            'HOSPITAL SANTO ANTONIO HSA': {'municipio': 420150, 'index_regional': 10},
            'HOSPITAL SANTO ANTONIO IMAS': {'municipio': 421810, 'index_regional': 7},
            'HOSPITAL SÃO BENEDITO': {'municipio': 420220, 'index_regional': 11},
            'HOSPÍTAL SÃO BERNARDO': {'municipio': 421420, 'index_regional': 14},
            'HOSPITAL SÃO BRÁS': {'municipio': 421360, 'index_regional': 15},
            'HOSPITAL SAO CAMILO': {'municipio': 420730, 'index_regional': 10},
            'HOSPITAL SÃO CRISTOVAO': {'municipio': 420530, 'index_regional': 17},
            'HOSPITAL SÃO DONATO': {'municipio': 420700, 'index_regional': 5},
            'HOSPITAL SÃO FRANCISCO': {'municipio': 420430, 'index_regional': 2},
            'HOSPITAL SÃO JORGE LTDA': {'municipio': 420780, 'index_regional': 2},
            'HOSPITAL SÃO JOSÉ CRICIUMA': {'municipio': 420460, 'index_regional': 5},
            'HOSPITAL SÃO JOSE DE URUBICI': {'municipio': 421890, 'index_regional': 16},
            'HOSPITAL SAO JOSE E MATERNIDADE CHIQUINHA GALLOTTI': {'municipio': 421800, 'index_regional': 9},
            'HOSPITAL SÃO JOSÉ E MATERNIDADE CHIQUINHA GALOTTI': {'municipio': 421800, 'index_regional': 9},
            'HOSPITAL SÃO JOSÉ JARAGUA DO SUL': {'municipio': 420890, 'index_regional': 13},
            'HOSPITAL SÃO JOSÉ MARAVILHA': {'municipio': 421050, 'index_regional': 6},
            'HOSPITAL SAO JUDAS TADEU': {'municipio': 421080, 'index_regional': 7},
            'HOSPITAL SÃO JUDAS TADEU': {'municipio': 421080, 'index_regional': 7},
            'HOSPITAL SÃO LUCAS': {'municipio': 421790, 'index_regional': 4},
            'HOSPITAL SÃO LUIZ': {'municipio': 420330, 'index_regional': 15},
            'HOSPITAL SÃO PEDRO': {'municipio': 420800, 'index_regional': 2},
            'HOSPITAL SÃO ROQUE': {'municipio': 421120, 'index_regional': 5},
            'HOSPITAL SÃO ROQUE DE LUZERNA': {'municipio': 421003, 'index_regional': 12},
            'HOSPITAL SAO ROQUE DE SEARA': {'municipio': 421750, 'index_regional': 2},
            'HOSPITAL SÃO ROQUE DE SEARA': {'municipio': 421750, 'index_regional': 2},
            'HOSPITAL SÃO SEBASTIÃO - ANITAPOLIS': {'municipio': 420110, 'index_regional': 9},
            'HOSPITAL SÃO SEBATIÃO - PAPANDUVA': {'municipio': 421220, 'index_regional': 15},
            'HOSPITAL SÃO SEBATIÃO - TREZE DE MAIO': {'municipio': 421840, 'index_regional': 10},
            'HOSPITAL SÃO VICENTE DE PAULO': {'municipio': 421010, 'index_regional': 15},
            'HOSPITAL SAUDADES': {'municipio': 421730, 'index_regional': 14},
            'HOSPITAL TEREZINHA GAIO BASO': {'municipio': 421720, 'index_regional': 6},
            'HOSPITAL TROMBUDO CENTRAL': {'municipio': 421860, 'index_regional': 3},
            'HOSPITAL UNIVERSITÁRIO': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL UNIVERSITARIO PEQUENO ANJO': {'municipio': 420820, 'index_regional': 8},
            'HOSPITAL VIDAL RAMOS': {'municipio': 421920, 'index_regional': 3},
            'HOSPITAL WALDOMIRO COLAUTTI': {'municipio': 420690, 'index_regional': 3},
            'HSS HOSPITAL SAO SEBASTIAO': {'municipio': 421880, 'index_regional': 7},
            'HSS HOSPITAL SÃO SEBATIÃO': {'municipio': 421880, 'index_regional': 7},
            'INSTITUTO DE PSIQUIATRIA IPQ': {'municipio': 421660, 'index_regional': 9},
            'INSTITUTO SANTE HOSPITAL DIONÍSIO CERQUEIRA': {'municipio': 420500, 'index_regional': 6},
            'MATERNIDADE CARMELA DUTRA': {'municipio': 420540, 'index_regional': 9},
            'MATERNIDADE DARCY VARGAS': {'municipio': 420910, 'index_regional': 13},
            'MATERNIDADE DONA CATARINA KUSS': {'municipio': 421010, 'index_regional': 15},
            'MATERNO INFANTIL SANTA CATARINA': {'municipio': 420460, 'index_regional': 5},
            'PRONTO ATENDIMENTO 24 HORAS ITAPOA': {'municipio': 420845, 'index_regional': 13},
            'SOCIEDADE CULTURAL E BENEFICENTE SÃO JOSE': {'municipio': 421450, 'index_regional': 3},
            'SOCIEDADE HOSP COMUN PE CLEMENTE KAMPMANN': {'municipio': 421110, 'index_regional': 15},
            'SOCIEDADE HOSPITALAR ITAPIRANGA': {'municipio': 420840, 'index_regional': 6},
            'UNIDADE DE PRONTO ATENDIMENTO UPA 24 H PADRE ALDO SEIDEL': {'municipio': 421010, 'index_regional': 15},
            'UNIDADE DE PRONTO ATENDIMENTO UPA VIDEIRA': {'municipio': 421930, 'index_regional': 4},
            'UNIDADE MISTA DE SAUDE NOSSA SENHORA DE SALETE': {'municipio': 420430, 'index_regional': 2},
        }
    def buscaInfoHospital(self, nome_hospital):
        # Tabela de regionais
        
        try:
            hospital = self.hospital[nome_hospital]
        except KeyError as ex:
            #print("!--- Hospital não encontrado: {", nome_hospital, "} ---!")
            hospital = -1
            raise Exception(
                "!--- Hospital não encontrado: {", nome_hospital, "} ---!")
        return hospital
