class processaLeitos:
    def __init__(self):
        self.hospital = {
            'ACENI': {'municipio': 420550, 'index_regional': 4},
            'ASSOCIACAO HOSPITALAR PE JOAO BERTHIER': {'municipio': 421600, 'index_regional': 14},
            'CEPON': {'municipio': 420540, 'index_regional': 9},
            'FUNDACAO HOSPITALAR SANTA OTILIA': {'municipio': 421170, 'index_regional': 5},
            'HOSPITAL SÃO DONATO': {'municipio': 420700, 'index_regional': 5},
            'HOSPITAL AZAMBUJA': {'municipio': 420290, 'index_regional': 11},
            'HOSPITAL BEIRA MAR': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL BEATRIZ RAMOS': {'municipio': 420750, 'index_regional': 11},
            'HOSPITAL BETHESDA': {'municipio': 420910, 'index_regional': 13},
            'HOSPITAL BOM JESUS': {'municipio': 420850, 'index_regional': 3},
            'HOSPITAL DA CRIANCA AUGUSTA MULLER BOHNER': {'municipio': 420420, 'index_regional': 14},
            'HOSPITAL DA FUNDACAO': {'municipio': 421690, 'index_regional': 17},
            'HOSPITAL DE CARIDADE CORACAO DE JESUS': {'municipio': 421650, 'index_regional': 16},
            'HOSPITAL DE CARIDADE DE JAGUARUNA': {'municipio': 420880, 'index_regional': 10},
            'HOSPITAL DE CARIDADE S B J DOS PASSOS': {'municipio': 420940, 'index_regional': 10},
            'HOSPITAL SÃO BRÁS': {'municipio': 421360, 'index_regional': 15},
            'HOSPITAL DE CARIDADE SAO ROQUE': {'municipio': 421120, 'index_regional': 5},
            'HOSPITAL FLORIANÓPOLIS': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL DE GASPAR': {'municipio': 420590, 'index_regional': 11},
            'HOSPITAL DOM JOAQUIM IMAS': {'municipio': 421770, 'index_regional': 7},
            'HOSPITAL DR JOSE ATHANAZIO': {'municipio': 420360, 'index_regional': 12},
            'HOSPITAL WALDOMIRO COLAUTTI': {'municipio': 420690, 'index_regional': 3},
            'HOSPITAL E MATERNIDADE JARAGUÁ': {'municipio': 420890, 'index_regional': 13},
            'HOSPITAL DE RETAGUARDA RIO MAINA': {'municipio': 420460, 'index_regional': 5},
            'HOSPITAL E MAT. MARIETA K. BORNHAUSEN': {'municipio': 420820, 'index_regional': 8},
            'HOSPITAL OASE': {'municipio': 421820, 'index_regional': 11},
            'HOSPITAL E MATERNIDADE RIO DO TESTO': {'municipio': 421320, 'index_regional': 11},
            'HOSPITAL SAGRADA FAMILIA': {'municipio': 421580, 'index_regional': 15},
            'HOSPITAL E MATERNIDADE SANTA CECILIA': {'municipio': 421550, 'index_regional': 4},
            'HOSPITAL E MATERNIDADE TEREZA RAMOS': {'municipio': 420930, 'index_regional': 16},
            'HOSPITAL FELIX DA COSTA GOMES': {'municipio': 421830, 'index_regional': 15},
            'HOSPITAL FREI BRUNO': {'municipio': 421970, 'index_regional': 17},
            'HOSPITAL GOVERNADOR CELSO RAMOS': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL HELIO ANJO ORTIZ': {'municipio': 420480, 'index_regional': 4},
            'HOSPITAL INFANTIL DR JESER AMARANTE FARIA': {'municipio': 420910, 'index_regional': 13},
            'HOSPITAL INFANTIL JOANA DE GUSMAO': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL UNIVERSITARIO PEQUENO ANJO': {'municipio': 420820, 'index_regional': 8},
            'HOSPITAL INFANTIL SEARA DO DO BEM': {'municipio': 420930, 'index_regional': 16},
            'HOSPITAL MAICE': {'municipio': 420300, 'index_regional': 4},
            'MATERNO INFANTIL SANTA CATARINA': {'municipio': 420460, 'index_regional': 5},
            'HOSPITAL MUNICIPAL RUTH CARDOSO': {'municipio': 420200, 'index_regional': 8},
            'HOSPITAL MUNICIPAL SÃO JOSÉ JOINVILLE': {'municipio': 420910, 'index_regional': 13},
            'HOSPITAL NEREU RAMOS': {'municipio': 420540, 'index_regional': 9},
            'HOSP. NOSSA SENHORA CONCEIÇÃO': {'municipio': 421870, 'index_regional': 10},
            'HOSPITAL NOSSA SENHORA DA CONCEICAO HNSC': {'municipio': 421900, 'index_regional': 5},
            'HOSPITAL NOSSA SENHORA DA IMACULADA CONCEICAO': {'municipio': 421150, 'index_regional': 9},
            'HOSPITAL NOSSA SENHORA DAS DORES': {'municipio': 420390, 'index_regional': 12},
            'HOSPITAL NOSSA SENHORA DAS GRACAS': {'municipio': 420260, 'index_regional': 16},
            'HOSPITAL NOSSA SENHORA DE FATIMA': {'municipio': 421380, 'index_regional': 7},
            'HOSPITAL PALMITOS': {'municipio': 421210, 'index_regional': 14},
            'HOSPITAL REGIONAL ALTO VALE': {'municipio': 421480, 'index_regional': 3},
            'HOSPITAL REGIONAL DE BIGUACU HELMUTH NASS': {'municipio': 420230, 'index_regional': 9},
            'HOSPITAL REGIONAL SÃO JOSÉ': {'municipio': 421660, 'index_regional': 9},
            'HOSPITAL REGIONAL DO OESTE': {'municipio': 420420, 'index_regional': 14},
            'HOSPITAL REGIONAL HANS DIETER': {'municipio': 420910, 'index_regional': 13},
            'HOSPITAL REGIONAL SÃO PAULO': {'municipio': 421950, 'index_regional': 17},
            'HOSPITAL TEREZINHA GAIO BASO': {'municipio': 421720, 'index_regional': 6},
            'HOSPITAL RIO NEGRINHO': {'municipio': 421500, 'index_regional': 15},
            'HOSPITAL DIVINO SALVADOR': {'municipio': 421900, 'index_regional': 4},
            'HOSPITAL SAMARIA': {'municipio': 421480, 'index_regional': 3},
            'HOSPITAL SANTA CLARA': {'municipio': 421175, 'index_regional': 16},
            'HOSPITAL SANTA CRUZ': {'municipio': 420380, 'index_regional': 15},
            'HOSPITAL SANTA ISABEL': {'municipio': 420240, 'index_regional': 11},
            'HOSPITAL SANTA TERESINHA': {'municipio': 420280, 'index_regional': 10},
            'HOSPITAL SANTO ANTONIO': {'municipio': 420240, 'index_regional': 11},
            'HOSPITAL SANTO ANTONIO GUARAMIRIM': {'municipio': 420650, 'index_regional': 13},
            'HOSPITAL SAO CAMILO': {'municipio': 420730, 'index_regional': 10},
            'HOSPITAL SÃO FRANCISCO': {'municipio': 420430, 'index_regional': 2},
            'HOSPITAL SAO FRANCISCO': {'municipio': 421570, 'index_regional': 9},
            'HOSPITAL SÃO JOSÉ CRICIUMA': {'municipio': 420460, 'index_regional': 5},
            'HOSPITAL SÃO JOSÉ JARAGUA DO SUL': {'municipio': 420890, 'index_regional': 13},
            'HOSPITAL SÃO JOSÉ MARAVILHA': {'municipio': 421050, 'index_regional': 6},
            'HOSPITAL SAO JOSE E MATERNIDADE CHIQUINHA GALLOTTI': {'municipio': 421800, 'index_regional': 9},
            'HOSPITAL SAO JUDAS TADEU': {'municipio': 421080, 'index_regional': 7},
            'HOSPITAL BENEFICENTE SAO ROQUE': {'municipio': 421003, 'index_regional': 12},
            'HOSPITAL SAO ROQUE DE SEARA': {'municipio': 421750, 'index_regional': 2},
            'HOSPITAL SÃO VICENTE DE PAULO': {'municipio': 421010, 'index_regional': 15},
            'HOSPITAL TROMBUDO CENTRAL': {'municipio': 421860, 'index_regional': 3},
            'HOSPITAL UNIVERSITÁRIO': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL SANTA TEREZINHA': {'municipio': 420900, 'index_regional': 12},
            'HSS HOSPITAL SAO SEBASTIAO': {'municipio': 421880, 'index_regional': 7},
            'HOSPITAL REGIONAL ARARANGUÁ': {'municipio': 420140, 'index_regional': 7},
            'HOSPITAL DE CARIDADE': {'municipio': 420540, 'index_regional': 9},
            'HOSPITAL INSTITUTO DE CARDIOLOGIA': {'municipio': 421660, 'index_regional': 9},
            'MATERNIDADE CARMELA DUTRA': {'municipio': 420540, 'index_regional': 9},
            'MATERNIDADE DARCY VARGAS': {'municipio': 420910, 'index_regional': 13},
            'SOCIEDADE HOSPITALAR ITAPIRANGA': {'municipio': 420840, 'index_regional': 6},
            'HOSPITAL NOSSA SENHORA DOS PRAZERES': {'municipio': 420930, 'index_regional': 16},
            'HOSPITAL MONSENHOR JOSE LOCKS DE SAO JOAO BATISTA': {'municipio': 421630, 'index_regional': 9},
            'ASSOCIACAO BENEFICENTE HOSPITAL SAO LUCAS': {'municipio': 420640, 'index_regional': 6},
            'UNIDADE DE PRONTO ATENDIMENTO UPA 24 H PADRE ALDO SEIDEL': {'municipio': 421010, 'index_regional': 15},

        }
    def buscaInfoHospital(self, nome_hospital):
        # Tabela de regionais
        
        try:
            hospital = self.hospital[nome_hospital]
        except KeyError as ex:
            #print("!--- Hospital não encontrado: {", nome_hospital, "} ---!")
            hospital = -1
            raise Exception(
                "!--- Hospital não encontrado: {", nome_hospital, "} ---!")
        return hospital
